spring.application.name=driver-leasing
spring.datasource.url=jdbc:mysql://localhost:3306/driver_leasing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.username=root
spring.datasource.password=Techno@0035
spring.security.user.name=user
spring.security.user.password=12345


# Disable open-in-view warning
spring.jpa.open-in-view=false

